### ISSUE TITLE
Help me to install it

### ISSUE THREAD

**Issue by solucionescol** [jpmens/from-traccar#1]
Hi:
i have traccar and mosquitto installed in same server, please tell me the way to install this.

thank you.

**Comment by solucionescol** [comment]
Sorry;

 i just found it; https://jpmens.net/2018/09/14/position-and-event-forwarding-from-traccar/

thank you again.

**Comment by solucionescol** [comment]
hi again:

I installed statsd and i have  the file "/usr/local/lib/libstatsdclient.so"

 when i run ft-run.sh i see error message
"./ft: error while loading shared libraries: libstatsdclient.so: cannot open shared object file: No such file or directory"
do you have idea what am i missing?
thank you

i created user jpm and  chown -R jpm:jpm /folder-located-from-traccar

i am running logged as root

**Comment by jpmens** [comment]
How did you install the statsd client, and then how did you build `ft`? If you are on Linux you might have to run `ldconfig -v` after installing a shared lib.

There should be no need to create a user called `jpm` ...

**Comment by solucionescol** [comment]
thank you very much..

Everything Is working ok now.

**Comment by techguy07** [comment]
Can you please help me in installing @solucionescol @jpmens i have mosquitto installed, done this on ft root directory and library loaded ldconfig -v, now how to run it

**Comment by jpmens** [comment]
You run it. Use supervisor or systemd or your shell or whatever to launch it and keep it running.

(please, in future, do not hijack a closed issue to ask questions)

**Comment by techguy07** [comment]
sure i m opening new ticket, sorry for that
